Rudimentary Reccomendation System
siesgstarena/labs pull request #2
Opened 2020-04-04 23:15 UTC by naidukarthi2193

## Created A Dashboard for Student Performance Analysis

## Type Of Change
- [ ] Bug Fix (non-breaking change that fixes an issue)
- [x] New Experiment
- [ ] Improving Experiment
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)

##TODO: Enhaced Recommendation system

2020-04-05 10:45 UTC, prabhuomkar commented
Appreciate your contribution @naidukarthi2193 :) 
Give us some time to review this PR.

2020-04-05 18:56 UTC, Swap76 approved these changes
Great Work Karthik :-)

2020-04-06 04:40 UTC, rsd511 approved these changes

2020-04-06 05:03 UTC, prabhuomkar requested changes

2020-04-06 05:03 UTC, prabhuomkar commented on student_analysis/functions.py
> +
Make sure the code is linted with pylint default configuration.

2020-04-06 05:03 UTC, prabhuomkar commented on student_analysis/requirements.txt
> +MarkupSafe==1.1.1
Update requirements.txt to have major requirements like 'Flask', 'matplotlib', 'numpy', 'pandas'.
Avoid versioning for individual dependent packages and overall.

2020-04-06 05:03 UTC, prabhuomkar commented on student_analysis/static/css/styles.css
> +
- Drop the stylesheets and javascript files which are not required. 
- Unless you are using custom stylesheets and javascript code, don't put the downloaded files here (like bootstrap css and jquery), instead use CDN links for bootstrap, jQuery

2020-04-06 05:03 UTC, prabhuomkar commented on student_analysis/problems.json
> +]
Dataset files can change over period of time. Add reference in your README from where you have to download dataset files and where you have to keep them for loading..
You may need to make some code changes for that. 

Reference: https://github.com/prabhuomkar/fiducia#dataset

2020-04-06 05:16 UTC, prabhuomkar commented
Good work @naidukarthi2193 
After first set of review:
- Please create an issue explaining about your experiment, we are tracking every PR against its Issue. We get more clarity over issues and space to discuss there and we can spend the space of PR to give comments/suggestions on code :)
- We need to standardize how we load data, usually in contributions like these our repository might get flooded with various versions of JSON files and we wan't to avoid this. Best way would be to have a `data` folder in your contributed folder and let users/us to download the latest version of dataset there and use it (easier to handler versions of data and the repo highlights only your code and not the redundant dataset part)
- Issue #3  has been created. Once the team has decided on how the contribution README should be, update this PR with that README template.

2020-04-06 09:58 UTC, shambhavisudarsan approved these changes

2020-04-06 12:45 UTC, naidukarthi2193 commented
Above Changes pushed to Repo
Added nltk_data for wordnet support

2020-04-06 13:20 UTC, merged